<?php

// Generated by GenAI\Container\Util\Dumper - do not edit by hand.
// Returns a Closure that populates a GenAI\Container\Container.
// require this file, then call the Closure with your container.

return function (\GenAI\Container\Container $c) {
    $c->register('GenAI\\Bundle\\Pdo\\PdoConfig', function (\GenAI\Container\Container $c) {
        return new \GenAI\Bundle\Pdo\PdoConfig();
    });
    $c->register('PDO', function (\GenAI\Container\Container $c) {
        return $c->get('GenAI\\Bundle\\Pdo\\PdoConfig')->pdo();
    });
    $c->register('Demo\\PingController', function (\GenAI\Container\Container $c) {
        return new \Demo\PingController($c->get('PDO'));
    });
};
