<?php

// Generated by GenAI\Routing\Util\RouteDumper - do not edit by hand.
// Returns a Closure that populates a GenAI\Routing\Router.
// require this file, then call the Closure with your router.

return function (\GenAI\Routing\Router $r) {
    $r->register('GET', '#^/db/ping$#', array(), 'Demo\\PingController@ping');
};
