<?php

// Generated by GenAI\Web\Processor\WebProcessor - do not edit by hand.

return array (
  'rest' => 
  array (
    'Demo\\PingController' => true,
  ),
  'engine' => NULL,
  'args' => 
  array (
    'Demo\\PingController@ping' => 
    array (
    ),
  ),
);
